/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthTrainersImport } from './routes/_auth/trainers'
import { Route as AuthPokemonsImport } from './routes/_auth/pokemons'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AuthBattlesImport } from './routes/_auth/battles'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthTrainersRoute = AuthTrainersImport.update({
  path: '/trainers',
  getParentRoute: () => AuthRoute,
} as any)

const AuthPokemonsRoute = AuthPokemonsImport.update({
  path: '/pokemons',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthBattlesRoute = AuthBattlesImport.update({
  path: '/battles',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/battles': {
      preLoaderRoute: typeof AuthBattlesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard': {
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/pokemons': {
      preLoaderRoute: typeof AuthPokemonsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/trainers': {
      preLoaderRoute: typeof AuthTrainersImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthBattlesRoute,
    AuthDashboardRoute,
    AuthPokemonsRoute,
    AuthTrainersRoute,
  ]),
])

/* prettier-ignore-end */
